title: John's vZome Models
author: John Kostick

description: > # this means to ignore newlines until "defaults:"
  Geometric designs and stories,
  all created with vZome (https://vzome.com).

defaults:
  - scope:
      path: ""
    values:
      # This description will be used for any page/post that does not defined its own description in its front-matter.
      description: A 3D design created in vZome.  Use your mouse or touch to interact.

header_pages:
- about.md

# Feel free to select a different theme.
# The "minima" theme is a good default choice just because it
#  generates a list of posts on the home page; many other themes do not.
theme: minima

exclude:
  # Don't generate pages from vZome-created README files,
  #  to avoid generating extra pages in Jekyll, which clutter up the
  #  header for the minima theme, and probably others.
  - 20*/*/*/*/README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
